version: '3.7'

services:

  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 54   

  chrome-node-1:
    image: selenium/node-chrome 
    shm_size: 2gb   
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-2:
    image: selenium/node-chrome
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-3:
    image: selenium/node-chrome
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-4:
    image: selenium/node-chrome    
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-5:
    image: selenium/node-chrome
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-6:
    image: selenium/node-chrome
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_START_XVFB: 'false'
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  worker-1:
    build: .
    command: celery -A app.scheduler.tasks-1:app worker -l info -c 2
    depends_on:
      - redis

  worker-2:
    build: .
    command: celery -A app.scheduler.tasks-2:app worker -l info -c 2
    depends_on:
      - redis

  worker-3:
    build: .
    command: celery -A app.scheduler.tasks-3:app worker -l info -c 2
    depends_on:
      - redis

  worker-4:
    build: .
    command: celery -A app.scheduler.tasks-4:app worker -l info -c 2
    depends_on:
      - redis

  worker-5:
    build: .
    command: celery -A app.scheduler.tasks-5:app worker -l info -c 2
    depends_on:
      - redis

  worker-6:
    build: .
    command: celery -A app.scheduler.tasks-6:app worker -l info -c 2
    depends_on:
      - redis

  worker-7:
    build: .
    command: celery -A app.scheduler.tasks-7:app worker -l info -c 2
    depends_on:
      - redis

  worker-8:
    build: .
    command: celery -A app.scheduler.tasks-8:app worker -l info -c 2
    depends_on:
      - redis

  worker-9:
    build: .
    command: celery -A app.scheduler.tasks-9:app worker -l info -c 2
    depends_on:
      - redis

  worker-10:
    build: .
    command: celery -A app.scheduler.tasks-10:app worker -l info -c 2
    depends_on:
      - redis

  beat-1:
    build: .
    command: celery -A app.scheduler.tasks-1:app beat -l info
    depends_on:
      - redis
  
  beat-2:
    build: .
    command: celery -A app.scheduler.tasks-2:app beat -l info
    depends_on:
      - redis
  
  beat-3:
    build: .
    command: celery -A app.scheduler.tasks-3:app beat -l info
    depends_on:
      - redis

  beat-4:
    build: .
    command: celery -A app.scheduler.tasks-4:app beat -l info
    depends_on:
      - redis

  beat-5:
    build: .
    command: celery -A app.scheduler.tasks-5:app beat -l info
    depends_on:
      - redis

  beat-6:
    build: .
    command: celery -A app.scheduler.tasks-6:app beat -l info
    depends_on:
      - redis

  beat-7:
    build: .
    command: celery -A app.scheduler.tasks-7:app beat -l info
    depends_on:
      - redis

  beat-8:
    build: .
    command: celery -A app.scheduler.tasks-8:app beat -l info
    depends_on:
      - redis

  beat-9:
    build: .
    command: celery -A app.scheduler.tasks-9:app beat -l info
    depends_on:
      - redis

  beat-10:
    build: .
    command: celery -A app.scheduler.tasks-10:app beat -l info
    depends_on:
      - redis
  worker-11:
    build: .
    command: celery -A app.scheduler.tasks-11:app worker -l info -c 2
    depends_on:
      - redis

  worker-12:
    build: .
    command: celery -A app.scheduler.tasks-12:app worker -l info -c 2
    depends_on:
      - redis

  worker-13:
    build: .
    command: celery -A app.scheduler.tasks-13:app worker -l info -c 2
    depends_on:
      - redis

  worker-14:
    build: .
    command: celery -A app.scheduler.tasks-14:app worker -l info -c 2
    depends_on:
      - redis

  worker-15:
    build: .
    command: celery -A app.scheduler.tasks-15:app worker -l info -c 2
    depends_on:
      - redis

  worker-16:
    build: .
    command: celery -A app.scheduler.tasks-16:app worker -l info -c 2
    depends_on:
      - redis

  worker-17:
    build: .
    command: celery -A app.scheduler.tasks-17:app worker -l info -c 2
    depends_on:
      - redis

  worker-18:
    build: .
    command: celery -A app.scheduler.tasks-18:app worker -l info -c 2
    depends_on:
      - redis

  worker-19:
    build: .
    command: celery -A app.scheduler.tasks-19:app worker -l info -c 2
    depends_on:
      - redis

  worker-20:
    build: .
    command: celery -A app.scheduler.tasks-20:app worker -l info -c 2
    depends_on:
      - redis

  worker-21:
    build: .
    command: celery -A app.scheduler.tasks-21:app worker -l info -c 2
    depends_on:
      - redis

  worker-22:
    build: .
    command: celery -A app.scheduler.tasks-22:app worker -l info -c 2
    depends_on:
      - redis

  beat-11:
    build: .
    command: celery -A app.scheduler.tasks-11:app beat -l info
    depends_on:
      - redis
  
  beat-12:
    build: .
    command: celery -A app.scheduler.tasks-12:app beat -l info
    depends_on:
      - redis
  
  beat-13:
    build: .
    command: celery -A app.scheduler.tasks-13:app beat -l info
    depends_on:
      - redis

  beat-14:
    build: .
    command: celery -A app.scheduler.tasks-14:app beat -l info
    depends_on:
      - redis

  beat-15:
    build: .
    command: celery -A app.scheduler.tasks-15:app beat -l info
    depends_on:
      - redis

  beat-16:
    build: .
    command: celery -A app.scheduler.tasks-16:app beat -l info
    depends_on:
      - redis

  beat-17:
    build: .
    command: celery -A app.scheduler.tasks-17:app beat -l info
    depends_on:
      - redis

  beat-18:
    build: .
    command: celery -A app.scheduler.tasks-18:app beat -l info
    depends_on:
      - redis

  beat-19:
    build: .
    command: celery -A app.scheduler.tasks-19:app beat -l info
    depends_on:
      - redis

  beat-20:
    build: .
    command: celery -A app.scheduler.tasks-20:app beat -l info
    depends_on:
      - redis

  beat-21:
    build: .
    command: celery -A app.scheduler.tasks-21:app beat -l info
    depends_on:
      - redis

  beat-22:
    build: .
    command: celery -A app.scheduler.tasks-22:app beat -l info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"