version: '3.7'

services:

  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  chrome-node-1:
    image: selenium/node-chrome 
 
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_NODE_SESSION_TIMEOUT: 1000
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
      SE_SESSION_REQUEST_TIMEOUT: 3600
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"120\",\"platformName\": \"linux\"}"

 
      
  worker-1:
    build: .
    command: celery -A app.scheduler.m-6.tasks-1:app worker -l info -c 1
    depends_on:
      selenium-hub:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: "redis:alpine"
