version: '3.7'

services:

  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 54   

  chrome-node-1:
    image: selenium/node-chrome    
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-2:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-3:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-4:
    image: selenium/node-chrome    
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-5:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-6:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"


  worker-1:
    build: .
    command: celery -A app.scheduler.tasks-1:app worker -l info -c 2
    depends_on:
      - redis

  worker-2:
    build: .
    command: celery -A app.scheduler.tasks-2:app worker -l info -c 2
    depends_on:
      - redis

  worker-3:
    build: .
    command: celery -A app.scheduler.tasks-3:app worker -l info -c 2
    depends_on:
      - redis

  worker-4:
    build: .
    command: celery -A app.scheduler.tasks-4:app worker -l info -c 2
    depends_on:
      - redis

  worker-5:
    build: .
    command: celery -A app.scheduler.tasks-5:app worker -l info -c 2
    depends_on:
      - redis

  worker-6:
    build: .
    command: celery -A app.scheduler.tasks-6:app worker -l info -c 2
    depends_on:
      - redis

  worker-7:
    build: .
    command: celery -A app.scheduler.tasks-7:app worker -l info -c 2
    depends_on:
      - redis

  worker-8:
    build: .
    command: celery -A app.scheduler.tasks-8:app worker -l info -c 2
    depends_on:
      - redis

  worker-9:
    build: .
    command: celery -A app.scheduler.tasks-9:app worker -l info -c 2
    depends_on:
      - redis

  worker-10:
    build: .
    command: celery -A app.scheduler.tasks-10:app worker -l info -c 2
    depends_on:
      - redis

  beat-1:
    build: .
    command: celery -A app.scheduler.tasks-1:app beat -l info
    depends_on:
      - redis
  
  beat-2:
    build: .
    command: celery -A app.scheduler.tasks-2:app beat -l info
    depends_on:
      - redis
  
  beat-3:
    build: .
    command: celery -A app.scheduler.tasks-3:app beat -l info
    depends_on:
      - redis

  beat-4:
    build: .
    command: celery -A app.scheduler.tasks-4:app beat -l info
    depends_on:
      - redis

  beat-5:
    build: .
    command: celery -A app.scheduler.tasks-5:app beat -l info
    depends_on:
      - redis

  beat-6:
    build: .
    command: celery -A app.scheduler.tasks-6:app beat -l info
    depends_on:
      - redis

  beat-7:
    build: .
    command: celery -A app.scheduler.tasks-7:app beat -l info
    depends_on:
      - redis

  beat-8:
    build: .
    command: celery -A app.scheduler.tasks-8:app beat -l info
    depends_on:
      - redis

  beat-9:
    build: .
    command: celery -A app.scheduler.tasks-9:app beat -l info
    depends_on:
      - redis

  beat-10:
    build: .
    command: celery -A app.scheduler.tasks-10:app beat -l info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"