version: '3.7'

services:

  worker:
    build: .
    command: celery -A app.scheduler.tasks:app worker -l info -c 10
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A app.scheduler.tasks:app beat -l info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"