version: '3.7'

services:

  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 54   

  chrome-node-1:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-2:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-3:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  chrome-node-4:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-5:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  chrome-node-6:
    image: selenium/node-chrome
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  # chrome-node-7:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  # chrome-node-8:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  # chrome-node-9:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"
    
  # chrome-node-10:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  # chrome-node-11:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  # chrome-node-12:
  #   image: selenium/node-chrome
  #   shm_size: 1gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     SE_EVENT_BUS_HOST: selenium-hub
  #     SE_EVENT_BUS_PUBLISH_PORT: 4442
  #     SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  #     SE_NODE_MAX_SESSIONS: 4
  #     SE_NODE_STEREOTYPE: "{\"browserName\":\"chrome\",\"browserVersion\":\"114\",\"platformName\": \"linux\"}"

  worker:
    build: .
    shm_size: 2gb
    command: celery -A app.scheduler.tasks:app worker -l info -c 5
    depends_on:
      - redis
      - selenium-hub
      - chrome-node-1
      - chrome-node-2
      - chrome-node-3
      - chrome-node-4
      - chrome-node-5
      - chrome-node-6
      # - chrome-node-7
      # - chrome-node-8
      # - chrome-node-9
      # - chrome-node-10
      # - chrome-node-11
      # - chrome-node-12

  beat:
    build: .
    command: celery -A app.scheduler.tasks:app beat -l info
    depends_on:
      - redis
      - selenium-hub
      - chrome-node-1
      - chrome-node-2
      - chrome-node-3
      - chrome-node-4
      - chrome-node-5
      - chrome-node-6
      # - chrome-node-7
      # - chrome-node-8
      # - chrome-node-9
      # - chrome-node-10
      # - chrome-node-11
      # - chrome-node-12

  redis:
    image: "redis:alpine"